// let BACKEND_ENDPOINT = "https://orders-manage-production.up.railway.app/";
let BACKEND_ENDPOINT = "http://localhost:8080/";
let API_ROOT_ENDPOINT = "api/com-diyadahara";

const API_ENDPOINTS = {
    CREATE_CUSTOMER: BACKEND_ENDPOINT + API_ROOT_ENDPOINT + "/create-customer",
    VIEW_ALL_CUSTOMERS: BACKEND_ENDPOINT + API_ROOT_ENDPOINT + "/view-all-customer",
    VIEW_SINGLE_CUSTOMER: BACKEND_ENDPOINT + API_ROOT_ENDPOINT + "/view-single-customer",
    DELTE_CUSTOMERS: BACKEND_ENDPOINT + API_ROOT_ENDPOINT + "/delete-customer",
    UPDATE_CUSTOMERS: BACKEND_ENDPOINT + API_ROOT_ENDPOINT + "/update-customer",

    VIEW_ALL_CATEGORY: BACKEND_ENDPOINT + API_ROOT_ENDPOINT + "/view-all-category",
    DELTE_CATEGORY: BACKEND_ENDPOINT + API_ROOT_ENDPOINT + "/delete-category-by-id",
    UPDATE_CATEGORY: BACKEND_ENDPOINT + API_ROOT_ENDPOINT + "/update-category-by-id",
    CREATE_CATEGORY: BACKEND_ENDPOINT + API_ROOT_ENDPOINT + "/create-category",
    GET_ALL_PRODUCT_SINGLE_CATEGORY: BACKEND_ENDPOINT + API_ROOT_ENDPOINT + "/view-single-product-by-type",

    CREATE_ORDER: BACKEND_ENDPOINT + API_ROOT_ENDPOINT + "/create-order",
    VIEWS_ORDER_SINGLE_CUSTOMER: BACKEND_ENDPOINT + API_ROOT_ENDPOINT + "/view-order-relevant-customer",

    VIEW_ALL_PRODUCT: BACKEND_ENDPOINT + API_ROOT_ENDPOINT + "/view-all-product",
    CREATE_PRODUCT: BACKEND_ENDPOINT + API_ROOT_ENDPOINT + "/create-product",
    UPDATE_PRODUCT: BACKEND_ENDPOINT + API_ROOT_ENDPOINT + "/update-single-product",
    DELTE_PRODUCT: BACKEND_ENDPOINT + API_ROOT_ENDPOINT + "/delete-single-product",


    ALL_DASHBOARD_DETIALS: BACKEND_ENDPOINT + API_ROOT_ENDPOINT + "/get-dashboard-details",

    ALL_TODAY_RELOAD_DETIALS: BACKEND_ENDPOINT + API_ROOT_ENDPOINT + "/view-all-reload",
    CREATE_RELOAD: BACKEND_ENDPOINT + API_ROOT_ENDPOINT + "/create-reload",
    DELETE_RELOAD: BACKEND_ENDPOINT + API_ROOT_ENDPOINT + "/delete-single-reload",
    VIEW_ALL_PREVIOUS_RELOAD: BACKEND_ENDPOINT + API_ROOT_ENDPOINT + "/view-all-reload-by-date",
    UPDATE_RELOAD: BACKEND_ENDPOINT + API_ROOT_ENDPOINT + "/update-single-reload",


    CREATE_EXPENSES: BACKEND_ENDPOINT + API_ROOT_ENDPOINT + "/create-expenses",
    DELTE_EXPENSES: BACKEND_ENDPOINT + API_ROOT_ENDPOINT + "/delete-single-expenses",
    UPDATE_EXPENSES: BACKEND_ENDPOINT + API_ROOT_ENDPOINT + "/update-single-expenses",
    VIEWALL_EXPENSES: BACKEND_ENDPOINT + API_ROOT_ENDPOINT + "/view-all-expenses",
    VIEW_ALL_PREVIOUSE_EXPENSES: BACKEND_ENDPOINT + API_ROOT_ENDPOINT + "/view-all-expenses-by-date",




}

export default API_ENDPOINTS;